stages:
  - build
  - test

# 빌드 단계
build:
  stage: build
  image: docker:latest
  variables:
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t rmh63/kbo:latest .
    - docker push rmh63/kbo:latest

