stages:
  - build
  - test

# 빌드 단계
build:
  stage: build
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://121.143.176.115:2375  # Docker Host 설정
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -t rmh63/kbo:latest .
    - docker push rmh63/kbo:latest

# 테스트 단계
test:
  stage: test
  image: openjdk:21-jdk
  script:
    - ./gradlew test  # Gradle 테스트 실행
