stages:          # 단계 정의
  - build
  - test
  - deploy

build_job:      # 빌드 단계
  stage: build
  image: ubuntu:20.04
  script:
    - echo "Building the project..."
    - ./build.sh  # 빌드 스크립트 또는 명령어

test_job:       # 테스트 단계
  stage: test
  image: ubuntu:20.04
  script:
    - echo "Running tests..."
    - ./run_tests.sh  # 테스트 스크립트 또는 명령어

deploy_job:     # 배포 단계
  stage: deploy
  image: ubuntu:20.04
  script:
    - echo "Deploying the application..."
    - ./deploy.sh  # 배포 스크립트 또는 명령어
  only:
    - master  # master 브랜치에만 배포
