stages:
  - build

build:
  stage: build
  image: docker:latest  # Docker 이미지를 사용
  services: []  # Docker-in-Docker 서비스 사용하지 않음
  script:
    - echo "Building the project..."
    - docker --version  # Docker 버전 확인